[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --alluredir=./allure-results
    --clean-alluredir
    --import-mode=importlib

testpaths = tests
pythonpath = .

markers =
    critical: Critical tests
    medium: Medium-priority tests
    security: Security and authorization tests
